name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - keras
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - tensorflow
  - xarray
  - zarr
  - rise
  - pydot
  - pydotplus
  - graphviz
  
